// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Card: typeof import('./src/components/Card.vue')['default']
    CardCart: typeof import('./src/components/CardCart.vue')['default']
    Modal: typeof import('./src/components/Modal.vue')['default']
  }
}

export {}
